// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Module extends pulumi.CustomResource {
    /**
     * Get an existing Module resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Module {
        return new Module(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'rdsmod:index:Module';

    /**
     * Returns true if the given object is an instance of Module.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Module {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Module.__pulumiType;
    }

    /**
     * The address of the RDS instance
     */
    declare public /*out*/ readonly db_instance_address: pulumi.Output<string | undefined>;
    /**
     * The ARN of the RDS instance
     */
    declare public /*out*/ readonly db_instance_arn: pulumi.Output<string | undefined>;
    /**
     * The availability zone of the RDS instance
     */
    declare public /*out*/ readonly db_instance_availability_zone: pulumi.Output<string | undefined>;
    /**
     * Specifies the identifier of the CA certificate for the DB instance
     */
    declare public /*out*/ readonly db_instance_ca_cert_identifier: pulumi.Output<string | undefined>;
    /**
     * Map of CloudWatch log groups created and their attributes
     */
    declare public /*out*/ readonly db_instance_cloudwatch_log_groups: pulumi.Output<{[key: string]: any} | undefined>;
    /**
     * The ID of the Directory Service Active Directory domain the instance is joined to
     */
    declare public /*out*/ readonly db_instance_domain: pulumi.Output<string | undefined>;
    /**
     * The ARN for the Secrets Manager secret with the self managed Active Directory credentials for the user joining the domain
     */
    declare public /*out*/ readonly db_instance_domain_auth_secret_arn: pulumi.Output<string | undefined>;
    /**
     * The IPv4 DNS IP addresses of your primary and secondary self managed Active Directory domain controllers
     */
    declare public /*out*/ readonly db_instance_domain_dns_ips: pulumi.Output<string[] | undefined>;
    /**
     * The fully qualified domain name (FQDN) of an self managed Active Directory domain
     */
    declare public /*out*/ readonly db_instance_domain_fqdn: pulumi.Output<string | undefined>;
    /**
     * The name of the IAM role to be used when making API calls to the Directory Service
     */
    declare public /*out*/ readonly db_instance_domain_iam_role_name: pulumi.Output<string | undefined>;
    /**
     * The self managed Active Directory organizational unit for your DB instance to join
     */
    declare public /*out*/ readonly db_instance_domain_ou: pulumi.Output<string | undefined>;
    /**
     * The connection endpoint
     */
    declare public /*out*/ readonly db_instance_endpoint: pulumi.Output<string | undefined>;
    /**
     * The database engine
     */
    declare public /*out*/ readonly db_instance_engine: pulumi.Output<string | undefined>;
    /**
     * The running version of the database
     */
    declare public /*out*/ readonly db_instance_engine_version_actual: pulumi.Output<string | undefined>;
    /**
     * The canonical hosted zone ID of the DB instance (to be used in a Route 53 Alias record)
     */
    declare public /*out*/ readonly db_instance_hosted_zone_id: pulumi.Output<string | undefined>;
    /**
     * The RDS instance identifier
     */
    declare public /*out*/ readonly db_instance_identifier: pulumi.Output<string | undefined>;
    /**
     * The ARN of the master user secret (Only available when manage_master_user_password is set to true)
     */
    declare public /*out*/ readonly db_instance_master_user_secret_arn: pulumi.Output<string | undefined>;
    /**
     * The database name
     */
    declare public /*out*/ readonly db_instance_name: pulumi.Output<string | undefined>;
    /**
     * The database port
     */
    declare public /*out*/ readonly db_instance_port: pulumi.Output<string | undefined>;
    /**
     * The RDS Resource ID of this instance
     */
    declare public /*out*/ readonly db_instance_resource_id: pulumi.Output<string | undefined>;
    /**
     * A map of DB Instance Identifiers and IAM Role ARNs separated by a comma
     */
    declare public readonly db_instance_role_associations: pulumi.Output<any | undefined>;
    /**
     * Specifies whether automatic rotation is enabled for the secret
     */
    declare public /*out*/ readonly db_instance_secretsmanager_secret_rotation_enabled: pulumi.Output<boolean | undefined>;
    /**
     * The RDS instance status
     */
    declare public /*out*/ readonly db_instance_status: pulumi.Output<string | undefined>;
    /**
     * The master username for the database
     */
    declare public /*out*/ readonly db_instance_username: pulumi.Output<string | undefined>;
    /**
     * Specifies the listener connection endpoint for SQL Server Always On
     */
    declare public /*out*/ readonly db_listener_endpoint: pulumi.Output<string | undefined>;
    /**
     * The ARN of the db option group
     */
    declare public /*out*/ readonly db_option_group_arn: pulumi.Output<any | undefined>;
    /**
     * The db option group id
     */
    declare public /*out*/ readonly db_option_group_id: pulumi.Output<any | undefined>;
    /**
     * The ARN of the db parameter group
     */
    declare public /*out*/ readonly db_parameter_group_arn: pulumi.Output<any | undefined>;
    /**
     * The db parameter group id
     */
    declare public /*out*/ readonly db_parameter_group_id: pulumi.Output<any | undefined>;
    /**
     * The ARN of the db subnet group
     */
    declare public /*out*/ readonly db_subnet_group_arn: pulumi.Output<any | undefined>;
    /**
     * The db subnet group name
     */
    declare public /*out*/ readonly db_subnet_group_id: pulumi.Output<any | undefined>;
    /**
     * The Amazon Resource Name (ARN) specifying the monitoring role
     */
    declare public /*out*/ readonly enhanced_monitoring_iam_role_arn: pulumi.Output<string | undefined>;
    /**
     * The name of the monitoring role
     */
    declare public /*out*/ readonly enhanced_monitoring_iam_role_name: pulumi.Output<string | undefined>;

    /**
     * Create a Module resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ModuleArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.identifier === undefined && !opts.urn) {
                throw new Error("Missing required property 'identifier'");
            }
            resourceInputs["allocated_storage"] = args?.allocated_storage;
            resourceInputs["allow_major_version_upgrade"] = args?.allow_major_version_upgrade;
            resourceInputs["apply_immediately"] = args?.apply_immediately;
            resourceInputs["auto_minor_version_upgrade"] = args?.auto_minor_version_upgrade;
            resourceInputs["availability_zone"] = args?.availability_zone;
            resourceInputs["backup_retention_period"] = args?.backup_retention_period;
            resourceInputs["backup_window"] = args?.backup_window;
            resourceInputs["blue_green_update"] = args?.blue_green_update;
            resourceInputs["ca_cert_identifier"] = args?.ca_cert_identifier;
            resourceInputs["character_set_name"] = args?.character_set_name;
            resourceInputs["cloudwatch_log_group_class"] = args?.cloudwatch_log_group_class;
            resourceInputs["cloudwatch_log_group_kms_key_id"] = args?.cloudwatch_log_group_kms_key_id;
            resourceInputs["cloudwatch_log_group_retention_in_days"] = args?.cloudwatch_log_group_retention_in_days;
            resourceInputs["cloudwatch_log_group_skip_destroy"] = args?.cloudwatch_log_group_skip_destroy;
            resourceInputs["cloudwatch_log_group_tags"] = args?.cloudwatch_log_group_tags;
            resourceInputs["copy_tags_to_snapshot"] = args?.copy_tags_to_snapshot;
            resourceInputs["create_cloudwatch_log_group"] = args?.create_cloudwatch_log_group;
            resourceInputs["create_db_instance"] = args?.create_db_instance;
            resourceInputs["create_db_option_group"] = args?.create_db_option_group;
            resourceInputs["create_db_parameter_group"] = args?.create_db_parameter_group;
            resourceInputs["create_db_subnet_group"] = args?.create_db_subnet_group;
            resourceInputs["create_monitoring_role"] = args?.create_monitoring_role;
            resourceInputs["custom_iam_instance_profile"] = args?.custom_iam_instance_profile;
            resourceInputs["db_instance_role_associations"] = args?.db_instance_role_associations;
            resourceInputs["db_instance_tags"] = args?.db_instance_tags;
            resourceInputs["db_name"] = args?.db_name;
            resourceInputs["db_option_group_tags"] = args?.db_option_group_tags;
            resourceInputs["db_parameter_group_tags"] = args?.db_parameter_group_tags;
            resourceInputs["db_subnet_group_description"] = args?.db_subnet_group_description;
            resourceInputs["db_subnet_group_name"] = args?.db_subnet_group_name;
            resourceInputs["db_subnet_group_tags"] = args?.db_subnet_group_tags;
            resourceInputs["db_subnet_group_use_name_prefix"] = args?.db_subnet_group_use_name_prefix;
            resourceInputs["dedicated_log_volume"] = args?.dedicated_log_volume;
            resourceInputs["delete_automated_backups"] = args?.delete_automated_backups;
            resourceInputs["deletion_protection"] = args?.deletion_protection;
            resourceInputs["domain"] = args?.domain;
            resourceInputs["domain_auth_secret_arn"] = args?.domain_auth_secret_arn;
            resourceInputs["domain_dns_ips"] = args?.domain_dns_ips;
            resourceInputs["domain_fqdn"] = args?.domain_fqdn;
            resourceInputs["domain_iam_role_name"] = args?.domain_iam_role_name;
            resourceInputs["domain_ou"] = args?.domain_ou;
            resourceInputs["enabled_cloudwatch_logs_exports"] = args?.enabled_cloudwatch_logs_exports;
            resourceInputs["engine"] = args?.engine;
            resourceInputs["engine_lifecycle_support"] = args?.engine_lifecycle_support;
            resourceInputs["engine_version"] = args?.engine_version;
            resourceInputs["family"] = args?.family;
            resourceInputs["final_snapshot_identifier_prefix"] = args?.final_snapshot_identifier_prefix;
            resourceInputs["iam_database_authentication_enabled"] = args?.iam_database_authentication_enabled;
            resourceInputs["identifier"] = args?.identifier;
            resourceInputs["instance_class"] = args?.instance_class;
            resourceInputs["instance_use_identifier_prefix"] = args?.instance_use_identifier_prefix;
            resourceInputs["iops"] = args?.iops;
            resourceInputs["kms_key_id"] = args?.kms_key_id;
            resourceInputs["license_model"] = args?.license_model;
            resourceInputs["maintenance_window"] = args?.maintenance_window;
            resourceInputs["major_engine_version"] = args?.major_engine_version;
            resourceInputs["manage_master_user_password"] = args?.manage_master_user_password;
            resourceInputs["manage_master_user_password_rotation"] = args?.manage_master_user_password_rotation;
            resourceInputs["master_user_password_rotate_immediately"] = args?.master_user_password_rotate_immediately;
            resourceInputs["master_user_password_rotation_automatically_after_days"] = args?.master_user_password_rotation_automatically_after_days;
            resourceInputs["master_user_password_rotation_duration"] = args?.master_user_password_rotation_duration;
            resourceInputs["master_user_password_rotation_schedule_expression"] = args?.master_user_password_rotation_schedule_expression;
            resourceInputs["master_user_secret_kms_key_id"] = args?.master_user_secret_kms_key_id;
            resourceInputs["max_allocated_storage"] = args?.max_allocated_storage;
            resourceInputs["monitoring_interval"] = args?.monitoring_interval;
            resourceInputs["monitoring_role_arn"] = args?.monitoring_role_arn;
            resourceInputs["monitoring_role_description"] = args?.monitoring_role_description;
            resourceInputs["monitoring_role_name"] = args?.monitoring_role_name;
            resourceInputs["monitoring_role_permissions_boundary"] = args?.monitoring_role_permissions_boundary;
            resourceInputs["monitoring_role_use_name_prefix"] = args?.monitoring_role_use_name_prefix;
            resourceInputs["multi_az"] = args?.multi_az;
            resourceInputs["nchar_character_set_name"] = args?.nchar_character_set_name;
            resourceInputs["network_type"] = args?.network_type;
            resourceInputs["option_group_description"] = args?.option_group_description;
            resourceInputs["option_group_name"] = args?.option_group_name;
            resourceInputs["option_group_skip_destroy"] = args?.option_group_skip_destroy;
            resourceInputs["option_group_timeouts"] = args?.option_group_timeouts;
            resourceInputs["option_group_use_name_prefix"] = args?.option_group_use_name_prefix;
            resourceInputs["options"] = args?.options;
            resourceInputs["parameter_group_description"] = args?.parameter_group_description;
            resourceInputs["parameter_group_name"] = args?.parameter_group_name;
            resourceInputs["parameter_group_skip_destroy"] = args?.parameter_group_skip_destroy;
            resourceInputs["parameter_group_use_name_prefix"] = args?.parameter_group_use_name_prefix;
            resourceInputs["parameters"] = args?.parameters;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["performance_insights_enabled"] = args?.performance_insights_enabled;
            resourceInputs["performance_insights_kms_key_id"] = args?.performance_insights_kms_key_id;
            resourceInputs["performance_insights_retention_period"] = args?.performance_insights_retention_period;
            resourceInputs["port"] = args?.port;
            resourceInputs["publicly_accessible"] = args?.publicly_accessible;
            resourceInputs["putin_khuylo"] = args?.putin_khuylo;
            resourceInputs["replica_mode"] = args?.replica_mode;
            resourceInputs["replicate_source_db"] = args?.replicate_source_db;
            resourceInputs["restore_to_point_in_time"] = args?.restore_to_point_in_time;
            resourceInputs["s3_import"] = args?.s3_import;
            resourceInputs["skip_final_snapshot"] = args?.skip_final_snapshot;
            resourceInputs["snapshot_identifier"] = args?.snapshot_identifier;
            resourceInputs["storage_encrypted"] = args?.storage_encrypted;
            resourceInputs["storage_throughput"] = args?.storage_throughput;
            resourceInputs["storage_type"] = args?.storage_type;
            resourceInputs["subnet_ids"] = args?.subnet_ids;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["timezone"] = args?.timezone;
            resourceInputs["upgrade_storage_config"] = args?.upgrade_storage_config;
            resourceInputs["username"] = args?.username;
            resourceInputs["vpc_security_group_ids"] = args?.vpc_security_group_ids;
            resourceInputs["db_instance_address"] = undefined /*out*/;
            resourceInputs["db_instance_arn"] = undefined /*out*/;
            resourceInputs["db_instance_availability_zone"] = undefined /*out*/;
            resourceInputs["db_instance_ca_cert_identifier"] = undefined /*out*/;
            resourceInputs["db_instance_cloudwatch_log_groups"] = undefined /*out*/;
            resourceInputs["db_instance_domain"] = undefined /*out*/;
            resourceInputs["db_instance_domain_auth_secret_arn"] = undefined /*out*/;
            resourceInputs["db_instance_domain_dns_ips"] = undefined /*out*/;
            resourceInputs["db_instance_domain_fqdn"] = undefined /*out*/;
            resourceInputs["db_instance_domain_iam_role_name"] = undefined /*out*/;
            resourceInputs["db_instance_domain_ou"] = undefined /*out*/;
            resourceInputs["db_instance_endpoint"] = undefined /*out*/;
            resourceInputs["db_instance_engine"] = undefined /*out*/;
            resourceInputs["db_instance_engine_version_actual"] = undefined /*out*/;
            resourceInputs["db_instance_hosted_zone_id"] = undefined /*out*/;
            resourceInputs["db_instance_identifier"] = undefined /*out*/;
            resourceInputs["db_instance_master_user_secret_arn"] = undefined /*out*/;
            resourceInputs["db_instance_name"] = undefined /*out*/;
            resourceInputs["db_instance_port"] = undefined /*out*/;
            resourceInputs["db_instance_resource_id"] = undefined /*out*/;
            resourceInputs["db_instance_secretsmanager_secret_rotation_enabled"] = undefined /*out*/;
            resourceInputs["db_instance_status"] = undefined /*out*/;
            resourceInputs["db_instance_username"] = undefined /*out*/;
            resourceInputs["db_listener_endpoint"] = undefined /*out*/;
            resourceInputs["db_option_group_arn"] = undefined /*out*/;
            resourceInputs["db_option_group_id"] = undefined /*out*/;
            resourceInputs["db_parameter_group_arn"] = undefined /*out*/;
            resourceInputs["db_parameter_group_id"] = undefined /*out*/;
            resourceInputs["db_subnet_group_arn"] = undefined /*out*/;
            resourceInputs["db_subnet_group_id"] = undefined /*out*/;
            resourceInputs["enhanced_monitoring_iam_role_arn"] = undefined /*out*/;
            resourceInputs["enhanced_monitoring_iam_role_name"] = undefined /*out*/;
        } else {
            resourceInputs["db_instance_address"] = undefined /*out*/;
            resourceInputs["db_instance_arn"] = undefined /*out*/;
            resourceInputs["db_instance_availability_zone"] = undefined /*out*/;
            resourceInputs["db_instance_ca_cert_identifier"] = undefined /*out*/;
            resourceInputs["db_instance_cloudwatch_log_groups"] = undefined /*out*/;
            resourceInputs["db_instance_domain"] = undefined /*out*/;
            resourceInputs["db_instance_domain_auth_secret_arn"] = undefined /*out*/;
            resourceInputs["db_instance_domain_dns_ips"] = undefined /*out*/;
            resourceInputs["db_instance_domain_fqdn"] = undefined /*out*/;
            resourceInputs["db_instance_domain_iam_role_name"] = undefined /*out*/;
            resourceInputs["db_instance_domain_ou"] = undefined /*out*/;
            resourceInputs["db_instance_endpoint"] = undefined /*out*/;
            resourceInputs["db_instance_engine"] = undefined /*out*/;
            resourceInputs["db_instance_engine_version_actual"] = undefined /*out*/;
            resourceInputs["db_instance_hosted_zone_id"] = undefined /*out*/;
            resourceInputs["db_instance_identifier"] = undefined /*out*/;
            resourceInputs["db_instance_master_user_secret_arn"] = undefined /*out*/;
            resourceInputs["db_instance_name"] = undefined /*out*/;
            resourceInputs["db_instance_port"] = undefined /*out*/;
            resourceInputs["db_instance_resource_id"] = undefined /*out*/;
            resourceInputs["db_instance_role_associations"] = undefined /*out*/;
            resourceInputs["db_instance_secretsmanager_secret_rotation_enabled"] = undefined /*out*/;
            resourceInputs["db_instance_status"] = undefined /*out*/;
            resourceInputs["db_instance_username"] = undefined /*out*/;
            resourceInputs["db_listener_endpoint"] = undefined /*out*/;
            resourceInputs["db_option_group_arn"] = undefined /*out*/;
            resourceInputs["db_option_group_id"] = undefined /*out*/;
            resourceInputs["db_parameter_group_arn"] = undefined /*out*/;
            resourceInputs["db_parameter_group_id"] = undefined /*out*/;
            resourceInputs["db_subnet_group_arn"] = undefined /*out*/;
            resourceInputs["db_subnet_group_id"] = undefined /*out*/;
            resourceInputs["enhanced_monitoring_iam_role_arn"] = undefined /*out*/;
            resourceInputs["enhanced_monitoring_iam_role_name"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["db_instance_username"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Module.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * The set of arguments for constructing a Module resource.
 */
export interface ModuleArgs {
    /**
     * The allocated storage in gigabytes
     */
    allocated_storage?: pulumi.Input<number>;
    /**
     * Indicates that major version upgrades are allowed. Changing this parameter does not result in an outage and the change is asynchronously applied as soon as possible
     */
    allow_major_version_upgrade?: pulumi.Input<boolean>;
    /**
     * Specifies whether any database modifications are applied immediately, or during the next maintenance window
     */
    apply_immediately?: pulumi.Input<boolean>;
    /**
     * Indicates that minor engine upgrades will be applied automatically to the DB instance during the maintenance window
     */
    auto_minor_version_upgrade?: pulumi.Input<boolean>;
    /**
     * The Availability Zone of the RDS instance
     */
    availability_zone?: pulumi.Input<string>;
    /**
     * The days to retain backups for
     */
    backup_retention_period?: pulumi.Input<number>;
    /**
     * The daily time range (in UTC) during which automated backups are created if they are enabled. Example: '09:46-10:16'. Must not overlap with maintenance_window
     */
    backup_window?: pulumi.Input<string>;
    /**
     * Enables low-downtime updates using RDS Blue/Green deployments.
     */
    blue_green_update?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Specifies the identifier of the CA certificate for the DB instance
     */
    ca_cert_identifier?: pulumi.Input<string>;
    /**
     * The character set name to use for DB encoding in Oracle instances. This can't be changed. See Oracle Character Sets Supported in Amazon RDS and Collations and Character Sets for Microsoft SQL Server for more information. This can only be set on creation
     */
    character_set_name?: pulumi.Input<string>;
    /**
     * Specified the log class of the log group. Possible values are: STANDARD or INFREQUENT_ACCESS
     */
    cloudwatch_log_group_class?: pulumi.Input<string>;
    /**
     * The ARN of the KMS Key to use when encrypting log data
     */
    cloudwatch_log_group_kms_key_id?: pulumi.Input<string>;
    /**
     * The number of days to retain CloudWatch logs for the DB instance
     */
    cloudwatch_log_group_retention_in_days?: pulumi.Input<number>;
    /**
     * Set to true if you do not wish the log group (and any logs it may contain) to be deleted at destroy time, and instead just remove the log group from the Terraform state
     */
    cloudwatch_log_group_skip_destroy?: pulumi.Input<boolean>;
    /**
     * Additional tags for the CloudWatch log group(s)
     */
    cloudwatch_log_group_tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * On delete, copy all Instance tags to the final snapshot
     */
    copy_tags_to_snapshot?: pulumi.Input<boolean>;
    /**
     * Determines whether a CloudWatch log group is created for each `enabled_cloudwatch_logs_exports`
     */
    create_cloudwatch_log_group?: pulumi.Input<boolean>;
    /**
     * Whether to create a database instance
     */
    create_db_instance?: pulumi.Input<boolean>;
    /**
     * Create a database option group
     */
    create_db_option_group?: pulumi.Input<boolean>;
    /**
     * Whether to create a database parameter group
     */
    create_db_parameter_group?: pulumi.Input<boolean>;
    /**
     * Whether to create a database subnet group
     */
    create_db_subnet_group?: pulumi.Input<boolean>;
    /**
     * Create IAM role with a defined name that permits RDS to send enhanced monitoring metrics to CloudWatch Logs
     */
    create_monitoring_role?: pulumi.Input<boolean>;
    /**
     * RDS custom iam instance profile
     */
    custom_iam_instance_profile?: pulumi.Input<string>;
    /**
     * A map of DB instance supported feature name to role association ARNs.
     */
    db_instance_role_associations?: pulumi.Input<{[key: string]: any}>;
    /**
     * Additional tags for the DB instance
     */
    db_instance_tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The DB name to create. If omitted, no database is created initially
     */
    db_name?: pulumi.Input<string>;
    /**
     * Additional tags for the DB option group
     */
    db_option_group_tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Additional tags for the  DB parameter group
     */
    db_parameter_group_tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Description of the DB subnet group to create
     */
    db_subnet_group_description?: pulumi.Input<string>;
    /**
     * Name of DB subnet group. DB instance will be created in the VPC associated with the DB subnet group. If unspecified, will be created in the default VPC
     */
    db_subnet_group_name?: pulumi.Input<string>;
    /**
     * Additional tags for the DB subnet group
     */
    db_subnet_group_tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Determines whether to use `subnet_group_name` as is or create a unique name beginning with the `subnet_group_name` as the prefix
     */
    db_subnet_group_use_name_prefix?: pulumi.Input<boolean>;
    /**
     * Use a dedicated log volume (DLV) for the DB instance. Requires Provisioned IOPS.
     */
    dedicated_log_volume?: pulumi.Input<boolean>;
    /**
     * Specifies whether to remove automated backups immediately after the DB instance is deleted
     */
    delete_automated_backups?: pulumi.Input<boolean>;
    /**
     * The database can't be deleted when this value is set to true
     */
    deletion_protection?: pulumi.Input<boolean>;
    /**
     * The ID of the Directory Service Active Directory domain to create the instance in
     */
    domain?: pulumi.Input<string>;
    /**
     * (Optional, but required if domain_fqdn is provided) The ARN for the Secrets Manager secret with the self managed Active Directory credentials for the user joining the domain. Conflicts with domain and domain_iam_role_name.
     */
    domain_auth_secret_arn?: pulumi.Input<string>;
    /**
     * (Optional, but required if domain_fqdn is provided) The IPv4 DNS IP addresses of your primary and secondary self managed Active Directory domain controllers. Two IP addresses must be provided. If there isn't a secondary domain controller, use the IP address of the primary domain controller for both entries in the list. Conflicts with domain and domain_iam_role_name.
     */
    domain_dns_ips?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The fully qualified domain name (FQDN) of the self managed Active Directory domain. Conflicts with domain and domain_iam_role_name.
     */
    domain_fqdn?: pulumi.Input<string>;
    /**
     * (Required if domain is provided) The name of the IAM role to be used when making API calls to the Directory Service
     */
    domain_iam_role_name?: pulumi.Input<string>;
    /**
     * (Optional, but required if domain_fqdn is provided) The self managed Active Directory organizational unit for your DB instance to join. Conflicts with domain and domain_iam_role_name.
     */
    domain_ou?: pulumi.Input<string>;
    /**
     * List of log types to enable for exporting to CloudWatch logs. If omitted, no logs will be exported. Valid values (depending on engine): alert, audit, error, general, listener, slowquery, trace, postgresql (PostgreSQL), upgrade (PostgreSQL)
     */
    enabled_cloudwatch_logs_exports?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The database engine to use
     */
    engine?: pulumi.Input<string>;
    /**
     * The life cycle type for this DB instance. This setting applies only to RDS for MySQL and RDS for PostgreSQL. Valid values are `open-source-rds-extended-support`, `open-source-rds-extended-support-disabled`. Default value is `open-source-rds-extended-support`.
     */
    engine_lifecycle_support?: pulumi.Input<string>;
    /**
     * The engine version to use
     */
    engine_version?: pulumi.Input<string>;
    /**
     * The family of the DB parameter group
     */
    family?: pulumi.Input<string>;
    /**
     * The name which is prefixed to the final snapshot on cluster destroy
     */
    final_snapshot_identifier_prefix?: pulumi.Input<string>;
    /**
     * Specifies whether or not the mappings of AWS Identity and Access Management (IAM) accounts to database accounts are enabled
     */
    iam_database_authentication_enabled?: pulumi.Input<boolean>;
    /**
     * The name of the RDS instance
     */
    identifier: pulumi.Input<string>;
    /**
     * The instance type of the RDS instance
     */
    instance_class?: pulumi.Input<string>;
    /**
     * Determines whether to use `identifier` as is or create a unique identifier beginning with `identifier` as the specified prefix
     */
    instance_use_identifier_prefix?: pulumi.Input<boolean>;
    /**
     * The amount of provisioned IOPS. Setting this implies a storage_type of 'io1' or `gp3`. See `notes` for limitations regarding this variable for `gp3`
     */
    iops?: pulumi.Input<number>;
    /**
     * The ARN for the KMS encryption key. If creating an encrypted replica, set this to the destination KMS ARN. If storage_encrypted is set to true and kms_key_id is not specified the default KMS key created in your account will be used. Be sure to use the full ARN, not a key alias.
     */
    kms_key_id?: pulumi.Input<string>;
    /**
     * License model information for this DB instance. Optional, but required for some DB engines, i.e. Oracle SE1
     */
    license_model?: pulumi.Input<string>;
    /**
     * The window to perform maintenance in. Syntax: 'ddd:hh24:mi-ddd:hh24:mi'. Eg: 'Mon:00:00-Mon:03:00'
     */
    maintenance_window?: pulumi.Input<string>;
    /**
     * Specifies the major version of the engine that this option group should be associated with
     */
    major_engine_version?: pulumi.Input<string>;
    /**
     * Set to true to allow RDS to manage the master user password in Secrets Manager
     */
    manage_master_user_password?: pulumi.Input<boolean>;
    /**
     * Whether to manage the master user password rotation. By default, false on creation, rotation is managed by RDS. Setting this value to false after previously having been set to true will disable automatic rotation.
     */
    manage_master_user_password_rotation?: pulumi.Input<boolean>;
    /**
     * Specifies whether to rotate the secret immediately or wait until the next scheduled rotation window.
     */
    master_user_password_rotate_immediately?: pulumi.Input<boolean>;
    /**
     * Specifies the number of days between automatic scheduled rotations of the secret. Either automatically_after_days or schedule_expression must be specified.
     */
    master_user_password_rotation_automatically_after_days?: pulumi.Input<number>;
    /**
     * The length of the rotation window in hours. For example, 3h for a three hour window.
     */
    master_user_password_rotation_duration?: pulumi.Input<string>;
    /**
     * A cron() or rate() expression that defines the schedule for rotating your secret. Either automatically_after_days or schedule_expression must be specified.
     */
    master_user_password_rotation_schedule_expression?: pulumi.Input<string>;
    /**
     *   The key ARN, key ID, alias ARN or alias name for the KMS key to encrypt the master user password secret in Secrets Manager.
     *   If not specified, the default KMS key for your Amazon Web Services account is used.
     */
    master_user_secret_kms_key_id?: pulumi.Input<string>;
    /**
     * Specifies the value for Storage Autoscaling
     */
    max_allocated_storage?: pulumi.Input<number>;
    /**
     * The interval, in seconds, between points when Enhanced Monitoring metrics are collected for the DB instance. To disable collecting Enhanced Monitoring metrics, specify 0. The default is 0. Valid Values: 0, 1, 5, 10, 15, 30, 60
     */
    monitoring_interval?: pulumi.Input<number>;
    /**
     * The ARN for the IAM role that permits RDS to send enhanced monitoring metrics to CloudWatch Logs. Must be specified if monitoring_interval is non-zero
     */
    monitoring_role_arn?: pulumi.Input<string>;
    /**
     * Description of the monitoring IAM role
     */
    monitoring_role_description?: pulumi.Input<string>;
    /**
     * Name of the IAM role which will be created when create_monitoring_role is enabled
     */
    monitoring_role_name?: pulumi.Input<string>;
    /**
     * ARN of the policy that is used to set the permissions boundary for the monitoring IAM role
     */
    monitoring_role_permissions_boundary?: pulumi.Input<string>;
    /**
     * Determines whether to use `monitoring_role_name` as is or create a unique identifier beginning with `monitoring_role_name` as the specified prefix
     */
    monitoring_role_use_name_prefix?: pulumi.Input<boolean>;
    /**
     * Specifies if the RDS instance is multi-AZ
     */
    multi_az?: pulumi.Input<boolean>;
    /**
     * The national character set is used in the NCHAR, NVARCHAR2, and NCLOB data types for Oracle instances. This can't be changed.
     */
    nchar_character_set_name?: pulumi.Input<string>;
    /**
     * The type of network stack to use
     */
    network_type?: pulumi.Input<string>;
    /**
     * The description of the option group
     */
    option_group_description?: pulumi.Input<string>;
    /**
     * Name of the option group
     */
    option_group_name?: pulumi.Input<string>;
    /**
     * Set to true if you do not wish the option group to be deleted at destroy time, and instead just remove the option group from the Terraform state
     */
    option_group_skip_destroy?: pulumi.Input<boolean>;
    /**
     * Define maximum timeout for deletion of `aws_db_option_group` resource
     */
    option_group_timeouts?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Determines whether to use `option_group_name` as is or create a unique name beginning with the `option_group_name` as the prefix
     */
    option_group_use_name_prefix?: pulumi.Input<boolean>;
    /**
     * A list of Options to apply
     */
    options?: any;
    /**
     * Description of the DB parameter group to create
     */
    parameter_group_description?: pulumi.Input<string>;
    /**
     * Name of the DB parameter group to associate or create
     */
    parameter_group_name?: pulumi.Input<string>;
    /**
     * Set to true if you do not wish the parameter group to be deleted at destroy time, and instead just remove the parameter group from the Terraform state
     */
    parameter_group_skip_destroy?: pulumi.Input<boolean>;
    /**
     * Determines whether to use `parameter_group_name` as is or create a unique name beginning with the `parameter_group_name` as the prefix
     */
    parameter_group_use_name_prefix?: pulumi.Input<boolean>;
    /**
     * A list of DB parameters (map) to apply
     */
    parameters?: pulumi.Input<pulumi.Input<{[key: string]: pulumi.Input<string>}>[]>;
    /**
     *   Password for the master DB user. Note that this may show up in logs, and it will be stored in the state file.
     *   The password provided will not be used if `manage_master_user_password` is set to true.
     */
    password?: pulumi.Input<string>;
    /**
     * Specifies whether Performance Insights are enabled
     */
    performance_insights_enabled?: pulumi.Input<boolean>;
    /**
     * The ARN for the KMS key to encrypt Performance Insights data
     */
    performance_insights_kms_key_id?: pulumi.Input<string>;
    /**
     * The amount of time in days to retain Performance Insights data. Valid values are `7`, `731` (2 years) or a multiple of `31`
     */
    performance_insights_retention_period?: pulumi.Input<number>;
    /**
     * The port on which the DB accepts connections
     */
    port?: pulumi.Input<string>;
    /**
     * Bool to control if instance is publicly accessible
     */
    publicly_accessible?: pulumi.Input<boolean>;
    /**
     * Do you agree that Putin doesn't respect Ukrainian sovereignty and territorial integrity? More info: https://en.wikipedia.org/wiki/Putin_khuylo!
     */
    putin_khuylo?: pulumi.Input<boolean>;
    /**
     * Specifies whether the replica is in either mounted or open-read-only mode. This attribute is only supported by Oracle instances. Oracle replicas operate in open-read-only mode unless otherwise specified
     */
    replica_mode?: pulumi.Input<string>;
    /**
     * Specifies that this resource is a Replicate database, and to use this value as the source database. This correlates to the identifier of another Amazon RDS Database to replicate
     */
    replicate_source_db?: pulumi.Input<string>;
    /**
     * Restore to a point in time (MySQL is NOT supported)
     */
    restore_to_point_in_time?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Restore from a Percona Xtrabackup in S3 (only MySQL is supported)
     */
    s3_import?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Determines whether a final DB snapshot is created before the DB instance is deleted. If true is specified, no DBSnapshot is created. If false is specified, a DB snapshot is created before the DB instance is deleted
     */
    skip_final_snapshot?: pulumi.Input<boolean>;
    /**
     * Specifies whether or not to create this database from a snapshot. This correlates to the snapshot ID you'd find in the RDS console, e.g: rds:production-2015-06-26-06-05
     */
    snapshot_identifier?: pulumi.Input<string>;
    /**
     * Specifies whether the DB instance is encrypted
     */
    storage_encrypted?: pulumi.Input<boolean>;
    /**
     * Storage throughput value for the DB instance. See `notes` for limitations regarding this variable for `gp3`
     */
    storage_throughput?: pulumi.Input<number>;
    /**
     * One of 'standard' (magnetic), 'gp2' (general purpose SSD), 'gp3' (new generation of general purpose SSD), or 'io1' (provisioned IOPS SSD). The default is 'io1' if iops is specified, 'gp2' if not. If you specify 'io1' or 'gp3' , you must also include a value for the 'iops' parameter
     */
    storage_type?: pulumi.Input<string>;
    /**
     * A list of VPC subnet IDs
     */
    subnet_ids?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A mapping of tags to assign to all resources
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Updated Terraform resource management timeouts. Applies to `aws_db_instance` in particular to permit resource management times
     */
    timeouts?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Time zone of the DB instance. timezone is currently only supported by Microsoft SQL Server. The timezone can only be set on creation. See MSSQL User Guide for more information
     */
    timezone?: pulumi.Input<string>;
    /**
     * Whether to upgrade the storage file system configuration on the read replica. Can only be set with replicate_source_db.
     */
    upgrade_storage_config?: pulumi.Input<boolean>;
    /**
     * Username for the master DB user
     */
    username?: pulumi.Input<string>;
    /**
     * List of VPC security groups to associate
     */
    vpc_security_group_ids?: pulumi.Input<pulumi.Input<string>[]>;
}
